🐞 fix(data): filter decorator keys
facing-dev/vue-facing-decorator pull request #59
Opened 2023-04-24 07:11 UTC by emeiziying

There will throw a error like '[Vue warn]: Data property "SET_AD" is already defined in Methods.' when I add something to computed or methods. So I add a filter condition to prevent item added to data.

2023-04-25 06:29 UTC, ruojianll requested changes

2023-04-25 06:29 UTC, ruojianll commented on src/option/data.ts
> +        return !!des.enumerable && !decoratorKeys.includes(name);
Should we merge 2 loops into `return !!des.enumerable && !CustomRecords.find(ite=>ite.key===name)` to improve performance?

2023-04-26 07:21 UTC, emeiziying commented on src/option/data.ts
> +        return !!des.enumerable && !decoratorKeys.includes(name);
In fact, I am modifying vuex-class to adapt vue-facing-decorator, the current decorator will have some problems, I will resubmit a modified version in a few days

2023-04-26 07:46 UTC, ruojianll commented on src/option/data.ts
> +        return !!des.enumerable && !decoratorKeys.includes(name);
Thank you.

2023-04-27 16:41 UTC, ruojianll requested changes
In stage3 decorators api, we can't access class's constructor function. So I provide a global CustomRecords array to collect custom decorator records. Whenever @Component called, we apply the collected records and clear them for next component(sorry for I forgetting to clear it). So I think we should keep the old CustomRecords strategy. The previous code you committed is good enough in the code structure.
In v-f-d v3, the code will be compatible with both decorators api state2 and state3. I will fill the gap but your docorator should accept only one arg option. e.g. `@YourDeoc({foo:'foo',bar:'bar'})` which accept one arg with all options, NOT `@YourDeco('foo','bar')` which accept more than one arg.

2023-04-27 16:41 UTC, ruojianll commented on src/custom/custom.ts
> +        const Ctor = typeof proto === 'function' ? proto : proto.constructor;
In stage3 decorators api, we can't access class's constructor function.

2023-04-27 16:45 UTC, ruojianll commented on src/component.ts
> -    })
Call `CustomRecords.splice(0,CustomRecords.length)` to clear CustomRecords after that.

2023-04-27 17:01 UTC, emeiziying commented
In general, there is no problem with this, but when I import vfd in both
vuex-class and vue projects, two CustomRecords will appear at the same time

Simmler Li ***@***.***>于2023年4月28日 周五00:41写道：

> ***@***.**** requested changes on this pull request.
>
> In stage3 decorators api, we can't access class's constructor function. So
> I provide a global CustomRecords array to collect custom decorator records.
> Whenever @component <https://github.com/component> called, we apply the
> collected records and clear them for next component(sorry for I forgetting
> to clear it). So I think we should keep the old CustomRecords strategy. The
> previous code you committed is good enough in the code struct.
> ------------------------------
>
> In src/custom/custom.ts
> <https://github.com/facing-dev/vue-facing-decorator/pull/59#discussion_r1179433417>
> :
>
> >  export function createDecorator(creator: Creator) {
>      return function (proto: any, key: string) {
> -        CustomRecords.push({
> -            key,
> -            creator
> -        })
> -    }
> -}
> -
> +        const Ctor = typeof proto === 'function' ? proto : proto.constructor;
>
> In stage3 decorators api, we can't access class's constructor function.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facing-dev/vue-facing-decorator/pull/59#pullrequestreview-1404469532>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPRL2PPBS4YOIQKTR5LQDDXDKOSXANCNFSM6AAAAAAXJEZGRY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-27 17:24 UTC, emeiziying commented
Thanks, I’ll try that

Simmler Li ***@***.***>于2023年4月28日 周五01:14写道：

> You probably need to set v-f-d as peer-dependencies, not install it in
> both vuex-class and vue projects. The files resolved from
> vuex-class/node-modulex/vue-facing-decorator/xxxx and
> vue-project/node-modulex/vue-facing-decorator/xxxx are not share one
> singleton.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facing-dev/vue-facing-decorator/pull/59#issuecomment-1526054816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPRL2MNKN3QYNEQBVE5MV3XDKSPDANCNFSM6AAAAAAXJEZGRY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-28 03:11 UTC, emeiziying commented
> In stage3 decorators api, we can't access class's constructor function. So I provide a global CustomRecords array to collect custom decorator records. Whenever @component called, we apply the collected records and clear them for next component(sorry for I forgetting to clear it). So I think we should keep the old CustomRecords strategy. The previous code you committed is good enough in the code structure. In v-f-d v3, the code will be compatible with both decorators api state2 and state3. I will fill the gap but your docorator should accept only one arg option. e.g. `@YourDeoc({foo:'foo',bar:'bar'})` which accept one arg with all options, NOT `@YourDeco('foo','bar')` which accept more than one arg.

In current case, the CustomRecords need be cleared after data build, it's asynchronous. This causes the decorator of other components to be inserted even if the records have not been cleared.

2023-04-28 06:50 UTC, ruojianll commented
Why it's asynchronous? JS applies class member decorators first, then applies class decorator one by one. And JS is a single thread runtime. We don't consider user cases in workers.

2023-04-28 07:15 UTC, ruojianll requested changes

2023-04-28 07:15 UTC, ruojianll commented on src/option/data.ts
> +    const computedAndMethodsKeyMap = new Map([...Object.keys(computed||{}),...Object.keys(methods||{})].map(e=>[e,1]))
Excluding these keys is not needed in this place.
For computed keys, they are already excluded in `excludeNames` function in line 16 
For method keys, they won't be collected by `getValidNames` because `getValidNames` is implemented by `getOwnPropertyDescriptors`, and methods are on the prototype.

But how do you exclude your custom decorator keys? The code is missing from the first commit.

2023-04-28 07:20 UTC, emeiziying commented
-

   Let me think again, write a little test case


Simmler Li ***@***.***> 于2023年4月28日周五 15:15写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/option/data.ts
> <https://github.com/facing-dev/vue-facing-decorator/pull/59#discussion_r1180016838>
> :
>
> >      optionBuilder.data ??= {}
>      const sample = new cons(optionBuilder, vueInstance)
>
> -    const decoratorMap = new Map(cons.__d?.map((e) => [e.key,1]) || []);
> +    const computedAndMethodsKeyMap = new Map([...Object.keys(computed||{}),...Object.keys(methods||{})].map(e=>[e,1]))
>
> Excluding these keys is not needed in this place.
> For computed keys, they are already excluded in excludeNames function in
> line 16
> For method keys, they won't be collected by getValidNames because
> getValidNames is implemented by getOwnPropertyDescriptors, and methods
> are on the prototype.
>
> But how do you exclude your custom decorator keys? The code is missing
> from the first commit.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facing-dev/vue-facing-decorator/pull/59#pullrequestreview-1405357534>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPRL2PQWRXOCIZT4UJOJGLXDNVA3ANCNFSM6AAAAAAXJEZGRY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-28 08:12 UTC, emeiziying commented
> Why it's asynchronous? JS applies class member decorators first then applies class decorator, one by one. And JS is a single thread runtime. We don't consider user cases in workers.

Parent and Children components will add decorators to records before both data initialze. So it's too late to clear records while built data.

2023-04-28 09:13 UTC, emeiziying commented on src/option/data.ts
> +    const computedAndMethodsKeyMap = new Map([...Object.keys(computed||{}),...Object.keys(methods||{})].map(e=>[e,1]))
> Excluding these keys is not needed in this place. For computed keys, they are already excluded in `excludeNames` function in line 16 For method keys, they won't be collected by `getValidNames` because `getValidNames` is implemented by `getOwnPropertyDescriptors`, and methods are on the prototype.
> 
> But how do you exclude your custom decorator keys? The code is missing from the first commit.

I finally found the issue. I add item to computed in CustomRecords loop which didn't add to slot computed map, so `excludeNames` did't work

2023-04-28 10:02 UTC, ruojianll commented
> > Why it's asynchronous? JS applies class member decorators first then applies class decorator, one by one. And JS is a single thread runtime. We don't consider user cases in workers.
> 
> Parent and Children components will add decorators to records before both data initialze. So it's too late to clear records while built data.

You are right, we could make a new map to the constructor's slot to contain records, I will PR some code to your fork.

2023-04-28 10:15 UTC, ruojianll approved these changes

2023-05-25 17:11 UTC, closed without merging