docs: provide example of provide
facing-dev/vue-facing-decorator pull request #67
Opened 2023-06-06 13:52 UTC by scscgit

The existing documentation makes it difficult to set up `provide` with correct types using a class-based component. Because [`@Provide`](https://github.com/kaorun343/vue-property-decorator#Provide) isn't supported anymore, there is also no direct migration step available. This example uses `this` to provide a type of the parent component, and it also shows how to make this property reactive using `computed` (implicitly imported from `@vue/reactivity`), which serves as a replacement of [`@ProvideReactive`](https://github.com/kaorun343/vue-property-decorator#ProvideReactive) + [`@InjectReactive`](https://github.com/kaorun343/vue-property-decorator#ProvideReactive).

🗒️ Below version Vue 3.3, `unwrapInjectedRef` configuration is supposed to be used as a workaround to support using `computed` without using ref on the inject side (otherwise it's notified as a console warning); here is a Nuxt 3 example for `app.vue`:
```vue
<script setup lang="ts">
// TODO: remove once this is default in Vue 3.3
useNuxtApp().vueApp.config.unwrapInjectedRef = true
</script>
```

2023-06-07 06:18 UTC, ruojianll commented
Wait until 3.0 release

2023-07-31 08:08 UTC, ruojianll requested changes
Should we put the example code into 'component > provide'?

2023-07-31 09:56 UTC, scscgit commented
Good idea, the `this` and `computed` are missing there; though I think it'll be still beneficial to link the [component > provide](https://facing-dev.github.io/vue-facing-decorator/#/en/class-component/component/component?id=provide) from the [injection usage](https://facing-dev.github.io/vue-facing-decorator/#/en/class-component/injection/injection?id=usage) page.

Will you make this change in a way that supports localization?

(Also as this will be superseded by #69, I still think it's worth providing this example of a reactive `@Component` usage.)

2023-07-31 11:09 UTC, ruojianll commented
@scscgit `@Provide` is a good idea. But https://github.com/facing-dev/vue-facing-decorator/pull/69 is not good enough now. I will mention you after that has be merged.

2023-10-16 23:09 UTC, closed without merging

2023-10-16 23:09 UTC, ruojianll commented
@scscgit #69 has been merged and will be released in next version.