+ correctly expose "methods"-option to recover compatibility to vue-class-component
facing-dev/vue-facing-decorator pull request #87
Opened 2023-09-18 20:02 UTC by tall1on

Hey, I noticed that the `methods` option doesn't work like the one from vue-class-components, so I added it. I also improved a bit of other code. Tests have all been passed, I edited the `methods` test to make sure it keeps working like in vue-class-components.

2023-09-18 20:05 UTC, fb-sean commented
Really needed thanks for the PR!

2023-09-20 07:50 UTC, ruojianll commented on src/component.ts
> +    //apply methods
Methods in class has already applied into `optoin.methods`, we just merge `arg.methods`.
```
if ('object' === typeof arg.methods && !Array.isArray(arg.methods) && arg.methods !== null) {
        option.methods??={}
        Object.assign(option.methods, arg.methods);
    }
```

2023-09-20 07:53 UTC, ruojianll commented on src/option/emit.ts
`methods` in slot is not necessary, so we don't change this file.

2023-09-20 07:57 UTC, ruojianll commented on src/option/methodsAndHooks.ts
Remove all codes about slot's `mehtods`

2023-09-20 08:00 UTC, ruojianll commented on src/utils.ts
> +    methods: Map<string, Function>
We don't need this since we changed codes in `component.ts`.

2023-09-20 08:03 UTC, ruojianll requested changes
I left some messages and hope you can improve it.

2023-09-20 16:28 UTC, tall1on commented
I guess i overthought it a bit 😅

I changed everything you asked, all tests passed.

2023-09-21 05:24 UTC, ruojianll approved these changes

2023-09-21 05:24 UTC, merged